#version 450

#extension GL_KHR_shader_subgroup_arithmetic: enable

layout(local_size_x = 128, local_size_y = 1, local_size_z = 1) in;

layout(std430,   binding=0) buffer layout_foo {
  uint foo[];
};

layout(std430,  binding=1) buffer layout_bar {
  uint bar;
};

void main() {
  uint value = subgroupMax(foo[gl_GlobalInvocationID.x]);

  // A single invocation in the subgroup will do the atomic operation
  if (subgroupElect()) {
    atomicMax(bar, value);
  }
}