FILE(GLOB SUBGROUP_SOURCE_FILES ${CMAKE_CURRENT_SOURCE_DIR}/*.cpp)
FILE(GLOB SUBGROUP_HEADER_FILES ${CMAKE_CURRENT_SOURCE_DIR}/*.h)

ADD_EXECUTABLE(subgroup ${SUBGROUP_SOURCE_FILES} ${SUBGROUP_HEADER_FILES} )
TARGET_LINK_LIBRARIES(subgroup vk-sample-common )
ADD_DEPENDENCIES(subgroup vk-sample-common)

# Vulkan dependies headers.
TARGET_INCLUDE_DIRECTORIES(subgroup PRIVATE ${CMAKE_CURRENT_SOURCE_DIR} )

INSTALL(TARGETS subgroup DESTINATION bin)
