INCLUDE(FetchContent)
IF(NOT TARGET assimp)
	FetchContent_Declare(assimp_source
		GIT_REPOSITORY https://github.com/assimp/assimp.git
		GIT_TAG "v6.0.2"
	)

	FetchContent_GetProperties(assimp_source)

	IF(NOT assimp_source)
		FetchContent_Populate(assimp_source)

		OPTION(ASSIMP_BUILD_TESTS OFF)
		OPTION(ASSIMP_BUILD_ASSIMP_VIEW OFF)
		OPTION(ASSIMP_BUILD_USD_IMPORTER ON)
		OPTION(ASSIMP_COVERALLS OFF)
		OPTION(ASSIMP_INJECT_DEBUG_POSTFIX OFF)
		OPTION(ASSIMP_WARNINGS_AS_ERRORS OFF)
		OPTION(ASSIMP_BUILD_ASSIMP_VIEW OFF)
		OPTION(ASSIMP_BUILD_ALL_EXPORTERS_BY_DEFAULT FALSE)
		OPTION(ASSIMP_DOUBLE_PRECISION OFF)

		ADD_SUBDIRECTORY(${assimp_source_SOURCE_DIR} ${assimp_source_BINARY_DIR} EXCLUDE_FROM_ALL)

	ELSE()
		MESSAGE(WARNING "Could not find assimp source code")
	ENDIF()
ENDIF()