FILE(GLOB SOURCE_PRIME_FILES ${CMAKE_CURRENT_SOURCE_DIR}/*.cpp)
FILE(GLOB HEADER_PRIME_FILES ${CMAKE_CURRENT_SOURCE_DIR}/*.h)

ADD_EXECUTABLE(Prime ${SOURCE_PRIME_FILES} ${HEADER_PRIME_FILES})
TARGET_LINK_LIBRARIES(Prime vk-sample-common)
ADD_DEPENDENCIES(Prime vk-sample-common)

TARGET_INCLUDE_DIRECTORIES(Prime PRIVATE ${CMAKE_CURRENT_SOURCE_DIR})

INSTALL(TARGETS Prime DESTINATION bin)