FILE(GLOB SOURCE_VECTOR_FIELD2D_FILES ${CMAKE_CURRENT_SOURCE_DIR}/*.cpp)
FILE(GLOB HEADER_VECTOR_FIELD2D_FILES ${CMAKE_CURRENT_SOURCE_DIR}/*.h)

#
ADD_EXECUTABLE(VectorField2D ${SOURCE_VECTOR_FIELD2D_FILES} ${HEADER_VECTOR_FIELD2D_FILES})
TARGET_LINK_LIBRARIES(VectorField2D vk-sample-common vk-sample-common-asset-importer)
ADD_DEPENDENCIES(VectorField2D vk-sample-common vk-sample-common-asset-importer)

# Vulkan dependies headers.
TARGET_INCLUDE_DIRECTORIES(VectorField2D PRIVATE ${CMAKE_CURRENT_SOURCE_DIR})

INSTALL(TARGETS VectorField2D DESTINATION bin)
