#version 460
#extension GL_ARB_separate_shader_objects : enable
#extension GL_ARB_compute_shader : enable
#extension GL_EXT_control_flow_attributes : enable
#extension GL_ARB_shading_language_include : enable
#extension GL_GOOGLE_include_directive : enable

layout(local_size_x = 128, local_size_y = 1, local_size_z = 4) in;

#include "base.glsl"

/*	*/
layout(std430, binding = 1) readonly buffer ReadBuffer { particle_t particle[]; }
readBuffer;
/*	*/
layout(std430, binding = 2) writeonly buffer WriteBuffer { particle_t particle[]; }
writeBuffer;

/*	*/
layout(std430, binding = 3) readonly buffer VectorField { vector_field_t field[]; }
vectorfield;

/**
 * Compute force influence from vector field.
 */
vec3 computeInfluence(const vec3 position) {

	const int infl = 2;
	const float amplitude = 1.0;
	const float virtualGridScale = 10.0;

	const uvec3 vectorBox = ubo.setting.particleBox.xyz;

	/*	Get position and position index.	*/
	const vec3 flopos = floor(position);
	const uvec3 ij = min(uvec3(flopos), vectorBox - (0, 0));

	/*	Compute total force.	*/
	vec3 force = vec3(0, 0, 0);
	for (uint y = 0; y < infl; y++) {

		for (uint x = 0; x < infl; x++) {

			/*	Compute position and memory location.	*/
			const uvec3 vpos = ij + uvec3(x, y, 0);
			const vec3 fvpos = flopos + vec3(x, y, 0);

			/*	Fetch vector force.	*/

			const uint index = (vpos.z * vectorBox.x * vpos.y * vectorBox.y) + (vpos.y * vectorBox.x) + vpos.x;
			const vec3 vecforce = vectorfield.field[index].force;

			/*	Compute influence force.	*/
			const float dist = distance(fvpos, position);
			const float distSquare = pow(dist, 2.0) * virtualGridScale;
			const float invDist = 1.0 / (distSquare + 0.01);

			/*	Sum Additional force.	*/
			force += (vecforce * invDist) * amplitude;
		}
	}

	return force;
}

/**
 * Compute motion influence from motion pointer.
 */
vec2 computeMotionInfluence(vec4 particle) {
	/*	*/
	float dist = distance(particle.xy, ubo.motion.pos);
	float infl = 1.0; // select(dist, ubo.motion.radius, isgreater(ubo.motion.radius, dist));

	return (1.0 / infl) * ubo.motion.velocity;
}

/**
 * Perform particle simulation with vector field.
 */
void main() {

	/*	Bounding Box of the simluation.	*/
	const vec3 max = ubo.setting.particleBox.xyz;
	const vec3 min = vec3(0, 0, 0);

	[[unroll]] for (uint i = 0; i < NR_Particles; i++) {}

	const uvec3 index = gl_GlobalInvocationID.xyz;

	/*	Particle index.	*/
	const uint pindex = index.x * index.y * index.z + index.y * index.z + index.z;

	/*  Get particle.   */
	vec3 position = readBuffer.particle[pindex].position;
	vec3 velocity = readBuffer.particle[pindex].velocity.xyz;
	const float invMass = readBuffer.particle[pindex].velocity.w;

	/*  Get vector of incluense. - Bilinear   */
	const vec3 forceInf = computeInfluence(position);
	/*  Compute total force.  */
	const vec3 force = (velocity + forceInf);

	/*  Add force to particle position. */
	velocity = force * invMass;
	/*	Update the position.	*/
	position = position + velocity * ubo.deltaTime;

	/*	Final position update.	*/
	position.xyz = clamp(position.xyz, min, max);

	/*	Update particle.	*/
	writeBuffer.particle[pindex].position = position;
	writeBuffer.particle[pindex].time = readBuffer.particle[pindex].time - ubo.deltaTime;
	writeBuffer.particle[pindex].velocity.xyz = velocity;
}

